import type { ParamDef, ShaderDefinition } from "./registry";
import { COLOR_MAP_PRESETS, COLOR_MAP_STOP_PARAMS } from "./color-map";
import asciiSource from "./wgsl/ascii.wgsl";
import bloomCompositeSource from "./wgsl/bloom-composite.wgsl";
import bloomExtractSource from "./wgsl/bloom-extract.wgsl";
import brandOverlayDetectSource from "./wgsl/brand-overlay-detect.wgsl";
import brandOverlaySource from "./wgsl/brand-overlay.wgsl";
import blurKawaseSource from "./wgsl/blur-kawase.wgsl";
import blurMotionSource from "./wgsl/blur-motion.wgsl";
import blurSeparableSource from "./wgsl/blur-separable.wgsl";
import colorMapSource from "./wgsl/color-map.wgsl";
import contrastSource from "./wgsl/contrast.wgsl";
import grainSource from "./wgsl/grain.wgsl";
import grayscaleSource from "./wgsl/grayscale.wgsl";
import hueSource from "./wgsl/hue.wgsl";
import kuwaharaAnisoSource from "./wgsl/kuwahara-aniso.wgsl";
import kuwaharaAnisoTensorSource from "./wgsl/kuwahara-aniso-tensor.wgsl";
import kuwaharaClassicSource from "./wgsl/kuwahara-classic.wgsl";
import kuwaharaPapariSource from "./wgsl/kuwahara-papari.wgsl";
import opacitySource from "./wgsl/opacity.wgsl";
import pixelSortSource from "./wgsl/pixel-sort.wgsl";
import saturationSource from "./wgsl/saturation.wgsl";
import snnSource from "./wgsl/snn.wgsl";
import tintSource from "./wgsl/tint.wgsl";
import tomitaTsujiSource from "./wgsl/tomita-tsuji.wgsl";
import vignetteSource from "./wgsl/vignette.wgsl";

export const CHARSET_PRESETS: { value: number; label: string; chars: string }[] = [
  { value: 0, label: "Standard", chars: "@#S08Xx+=-;:,. " },
  {
    value: 1,
    label: "Detailed",
    chars: "$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\\|()1{}[]?-_+~<>i!lI;:,\"^`'. ",
  },
  { value: 2, label: "Minimal", chars: ".:-=+*#%@" },
  { value: 3, label: "Blocks", chars: "█▓▒░ " },
  { value: 4, label: "Custom", chars: "" },
];

export function charsetFromParams(params: Record<string, unknown>): string {
  const preset = Number(params.charset_preset ?? 0);
  if (preset === 4) {
    const custom = String(params.charset ?? "");
    return custom.length > 0 ? custom : CHARSET_PRESETS[0].chars;
  }
  return CHARSET_PRESETS[preset]?.chars ?? CHARSET_PRESETS[0].chars;
}

const radiusInt = (max: number, def: number, description: string) =>
  ({
    type: "int" as const,
    key: "radius",
    label: "Radius",
    min: 1,
    max,
    default: def,
    description,
  });

const PIXEL_SORT_INTERVALS = [
  { value: 0, label: "Threshold" },
  { value: 1, label: "Edges" },
  { value: 2, label: "Random" },
  { value: 3, label: "Waves" },
];

const PIXEL_SORT_KEYS = [
  { value: 0, label: "Luminance" },
  { value: 1, label: "Lightness" },
  { value: 2, label: "Hue" },
  { value: 3, label: "Saturation" },
  { value: 4, label: "Intensity" },
  { value: 5, label: "Minimum" },
  { value: 6, label: "Maximum" },
  { value: 7, label: "Red" },
  { value: 8, label: "Green" },
  { value: 9, label: "Blue" },
];

function pixelSortParams(includeAxis: boolean): ParamDef[] {
  const axis: ParamDef[] = includeAxis
    ? [
        {
          type: "select",
          key: "axis",
          label: "Axis",
          options: [
            { value: 0, label: "Horizontal" },
            { value: 1, label: "Vertical" },
          ],
          default: 0,
          description: "Sort along rows (horizontal streaks) or columns (vertical streaks).",
        },
      ]
    : [];
  return [
    ...axis,
    {
      type: "select",
      key: "interval",
      label: "Mask by",
      options: PIXEL_SORT_INTERVALS,
      default: 0,
      description:
        "How sortable runs are split. Threshold: luma in range. Edges: Sobel barriers. Random / Waves: run lengths. A Blend mask always splits runs too.",
    },
    {
      type: "select",
      key: "sort_by",
      label: "Sort by",
      options: PIXEL_SORT_KEYS,
      default: 0,
    },
    {
      type: "int",
      key: "max_span",
      label: "Max span",
      min: 2,
      max: 64,
      default: 32,
      description: "Longest run sorted, in pixels. Longer streaks cost more GPU time.",
    },
    { type: "bool", key: "reverse", label: "Reverse", default: true, description: "Bright (or high-key) pixels first." },
    {
      type: "bool",
      key: "invert_interval",
      label: "Invert mask",
      default: false,
      description: "Flip which pixels belong to a sortable run (does not invert the Blend mask).",
    },
    {
      type: "float",
      key: "lower",
      label: "Lower",
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.25,
      description: "Threshold: minimum luma. Edges: Sobel amount that breaks a run.",
    },
    {
      type: "float",
      key: "upper",
      label: "Upper",
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.8,
      description: "Threshold: maximum luma. Pixels outside [Lower, Upper] stay put and split runs.",
    },
    {
      type: "float",
      key: "length",
      label: "Length",
      min: 2,
      max: 200,
      step: 1,
      default: 24,
      description: "Characteristic run length for Random and Waves, in pixels.",
    },
    {
      type: "float",
      key: "strength",
      label: "Strength",
      min: 0,
      max: 1,
      step: 0.01,
      default: 1,
    },
  ];
}

export const EXTRA_SHADERS: ShaderDefinition[] = [
  {
    id: "kuwahara-classic",
    name: "Kuwahara (classic)",
    group: "Painterly",
    description: "Original 4-quadrant Kuwahara: overlapping boxes, keep the lowest-variance mean.",
    source: kuwaharaClassicSource,
    params: [radiusInt(8, 3, "Half-width of each quadrant, in source pixels.")],
  },
  {
    id: "kuwahara-papari",
    name: "Kuwahara (Papari)",
    group: "Painterly",
    description:
      "Papari extension: circular 8-sector kernel, polynomial weights, and a soft inverse-variance blend.",
    source: kuwaharaPapariSource,
    params: [
      radiusInt(8, 4, "Kernel radius in source pixels."),
      {
        type: "float",
        key: "sharpness",
        label: "Sharpness",
        min: 0.1,
        max: 8,
        step: 0.05,
        default: 2,
        description: "How strongly low-variance sectors win the blend. Higher is closer to a hard pick.",
      },
    ],
  },
  {
    id: "kuwahara-anisotropic",
    name: "Kuwahara (anisotropic)",
    group: "Painterly",
    description:
      "Structure-tensor Kuwahara: elliptical sectors follow local edges. Two GPU passes (tensor then filter).",
    passes: [{ source: kuwaharaAnisoTensorSource }, { source: kuwaharaAnisoSource }],
    params: [
      radiusInt(5, 3, "Ellipse radius in source pixels. Higher is much more expensive."),
      {
        type: "float",
        key: "eccentricity",
        label: "Eccentricity",
        min: 0,
        max: 4,
        step: 0.05,
        default: 1.5,
        description: "How strongly the kernel stretches along edges.",
      },
      {
        type: "float",
        key: "sharpness",
        label: "Sharpness",
        min: 0.1,
        max: 8,
        step: 0.05,
        default: 2,
      },
    ],
  },
  {
    id: "tomita-tsuji",
    name: "Tomita–Tsuji",
    group: "Painterly",
    description: "Five overlapping windows (four corners plus centre); pick the lowest-variance mean.",
    source: tomitaTsujiSource,
    params: [radiusInt(6, 2, "Window radius. Classic Tomita–Tsuji is a 5×5 (radius 2).")],
  },
  {
    id: "snn",
    name: "Symmetric nearest neighbour",
    group: "Painterly",
    description:
      "For each opposite pair of pixels, keep the one closer to the centre colour, then average. Cheap edge-preserving smooth.",
    source: snnSource,
    params: [radiusInt(8, 2, "Chebyshev radius of paired samples.")],
  },
  {
    id: "ascii",
    name: "ASCII",
    group: "ASCII",
    description:
      "Map brightness to glyphs from a character ramp. Custom sets, source colour, contrast, coverage and edge emphasis.",
    source: asciiSource,
    usesAtlas: true,
    params: [
      {
        type: "float",
        key: "cell_size",
        label: "Cell size",
        min: 4,
        max: 64,
        step: 1,
        default: 10,
        description: "Glyph cell size in source pixels.",
      },
      {
        type: "select",
        key: "charset_preset",
        label: "Character set",
        options: CHARSET_PRESETS.map(({ value, label }) => ({ value, label })),
        default: 0,
      },
      {
        type: "string",
        key: "charset",
        label: "Custom characters",
        default: "@#S08Xx+=-;:,. ",
        placeholder: "Dark → light",
        description: "Used when Character set is Custom. Dense glyphs first for dark areas.",
      },
      {
        type: "float",
        key: "contrast",
        label: "Contrast",
        min: 0.2,
        max: 4,
        step: 0.05,
        default: 1.2,
      },
      { type: "bool", key: "invert", label: "Invert", default: false },
      {
        type: "select",
        key: "color_mode",
        label: "Color",
        options: [
          { value: 0, label: "Ink" },
          { value: 1, label: "Source" },
        ],
        default: 0,
      },
      { type: "color", key: "ink", label: "Ink", default: [0.95, 0.95, 0.92] },
      { type: "color", key: "background", label: "Background", default: [0.05, 0.05, 0.06] },
      {
        type: "float",
        key: "coverage",
        label: "Coverage",
        min: 0,
        max: 1,
        step: 0.01,
        default: 1,
        description: "Cells brighter than this stay as background.",
      },
      {
        type: "float",
        key: "edge",
        label: "Edge emphasis",
        min: 0,
        max: 2,
        step: 0.01,
        default: 0,
        description: "Adds Sobel edges into the brightness used to pick a glyph.",
      },
    ],
  },
  {
    id: "brand-overlay",
    name: "Brand overlay",
    group: "Stylized",
    description:
      "Survey-drawing overlay: contrast-aware marks, a distance mesh with sized markers, a shrinking circle chain, and colour-mapped mosaic squares on hashed anchors (WeatherNext by default).",
    usesAtlas: true,
    atlasStyle: "label",
    atlasCharset: "0123456789,",
    passes: [{ source: brandOverlayDetectSource }, { source: brandOverlaySource }],
    params: [
      {
        type: "int",
        key: "zone_count",
        label: "Zone count",
        min: 0,
        max: 8,
        default: 3,
        description: "Colour-mapped squares snapped to high-score anchors. 0 hides them.",
      },
      {
        type: "float",
        key: "pixel_size",
        label: "Pixel size",
        min: 2,
        max: 60,
        step: 2,
        default: 20,
        description: "Mosaic block size inside each zone, before the palette remap.",
      },
      {
        type: "float",
        key: "zone_size",
        label: "Zone size",
        min: 20,
        max: 400,
        step: 10,
        default: 130,
        description: "Half-width of each colour-map square, in source pixels.",
      },
      {
        type: "bool",
        key: "zone_stroke",
        label: "Zone stroke",
        default: true,
        description: "Outline each colour-map square.",
      },
      {
        type: "select",
        key: "map_preset",
        label: "Zone palette",
        options: COLOR_MAP_PRESETS.filter((p) => p.value !== 6).map(({ value, label }) => ({ value, label })),
        default: 0,
        description: "Palette used inside the squares. WeatherNext is the blue sky ramp.",
      },
      { type: "bool", key: "chain_enabled", label: "Chain", default: true },
      {
        type: "int",
        key: "chain_count",
        label: "Chain count",
        min: 3,
        max: 15,
        default: 10,
        description: "Number of circles in the chain.",
      },
      {
        type: "float",
        key: "chain_angle",
        label: "Chain angle",
        min: 0,
        max: 180,
        step: 1,
        default: 45,
        description: "Direction of the chain. 0 is vertical, 45 diagonal, 90 horizontal.",
      },
      {
        type: "float",
        key: "chain_base",
        label: "Base radius",
        min: 30,
        max: 400,
        step: 5,
        default: 250,
        description: "Radius of the centre chain circle.",
      },
      {
        type: "float",
        key: "chain_ratio",
        label: "Size ratio",
        min: 0.5,
        max: 1.2,
        step: 0.01,
        default: 0.79,
        description: "Size multiplier per step. Below 1 shrinks outward from the centre.",
      },
      { type: "bool", key: "intersections", label: "Intersections", default: true },
      {
        type: "float",
        key: "marker_size",
        label: "Marker size",
        min: 2,
        max: 15,
        step: 0.5,
        default: 5,
        description: "Dot size at each adjacent-circle intersection.",
      },
      {
        type: "select",
        key: "detect_mode",
        label: "Detection",
        options: [
          { value: 0, label: "Combined" },
          { value: 1, label: "Contrast" },
          { value: 2, label: "Bright" },
          { value: 3, label: "Dark" },
        ],
        default: 0,
      },
      {
        type: "float",
        key: "block_size",
        label: "Block size",
        min: 2,
        max: 64,
        step: 1,
        default: 16,
        description: "Analysis grid resolution, in source pixels. Smaller = more detail.",
      },
      {
        type: "float",
        key: "threshold",
        label: "Threshold",
        min: 0,
        max: 100,
        step: 1,
        default: 49,
        description: "Minimum score to place a mark. Higher = fewer, stronger hits.",
      },
      {
        type: "int",
        key: "max_circles",
        label: "Max marks",
        min: 1,
        max: 300,
        step: 1,
        default: 95,
        description: "Upper bound on how many marks are placed. Uses even spacing across the frame, so 200 on a 1080² image is about 200 hits if the threshold allows.",
      },
      {
        type: "float",
        key: "min_distance",
        label: "Min distance",
        min: 10,
        max: 100,
        step: 5,
        default: 40,
        description: "Minimum gap between mark centres. Lower packs more marks (until Max marks).",
      },
      {
        type: "select",
        key: "shape",
        label: "Shape",
        options: [
          { value: 0, label: "Circle" },
          { value: 1, label: "Square" },
        ],
        default: 1,
      },
      {
        type: "float",
        key: "min_radius",
        label: "Min radius",
        min: 2,
        max: 30,
        step: 1,
        default: 4,
        description: "Smallest mark size (low-score regions).",
      },
      {
        type: "float",
        key: "max_radius",
        label: "Max radius",
        min: 10,
        max: 120,
        step: 2,
        default: 24,
        description: "Largest mark size (high-score regions).",
      },
      {
        type: "float",
        key: "stroke",
        label: "Stroke",
        min: 0,
        max: 2,
        step: 0.05,
        default: 0.5,
        description: "Outline thickness for marks, chain, and zone frames. 0 hides outlines.",
      },
      {
        type: "int",
        key: "size_seed",
        label: "Size seed",
        min: 1,
        max: 999,
        default: 42,
        description: "Random seed for size jitter, density, and zone placement.",
      },
      {
        type: "float",
        key: "label_size",
        label: "Label size",
        min: 0,
        max: 30,
        step: 1,
        default: 8,
        description: "Font size of x,y coordinate labels (real type, not a bitmap). 0 hides them.",
      },
      {
        type: "float",
        key: "overlay_opacity",
        label: "Overlay opacity",
        min: 0,
        max: 1,
        step: 0.05,
        default: 1,
        description: "Master opacity for marks, lines, dots, labels, and strokes.",
      },
      {
        type: "float",
        key: "max_distance",
        label: "Max distance",
        min: 0,
        max: 400,
        step: 10,
        default: 110,
        description: "Connect two markers with a line only when their centres are closer than this. 0 hides the mesh edges.",
      },
      {
        type: "float",
        key: "line_weight",
        label: "Line weight",
        min: 0,
        max: 2,
        step: 0.05,
        default: 0.5,
        description: "Thickness of connecting lines. 0 hides mesh edges.",
      },
      {
        type: "float",
        key: "mesh_marker",
        label: "Mesh marker",
        min: 0,
        max: 20,
        step: 0.5,
        default: 3.5,
        description: "Filled marker at each detected point. 0 hides the mesh nodes.",
      },
      { type: "color", key: "ink", label: "Ink", default: [0.93, 0.925, 0.91] },
    ],
  },
  {
    id: "pixel-sort",
    name: "Pixel sort",
    group: "Stylized",
    description:
      "Asendorf-style interval sort along a row or column. Threshold, edges, random and waves mask which runs get sorted; assign a Blend mask to split intervals further.",
    source: pixelSortSource,
    usesLayerMask: true,
    params: pixelSortParams(true),
  },
  {
    id: "pixel-sort-hv",
    name: "Pixel sort (HV)",
    group: "Stylized",
    description:
      "Two-pass pixel sort: horizontal, then vertical. Same masked interval modes as Pixel sort.",
    usesLayerMask: true,
    passes: [
      { source: pixelSortSource, constants: { axis: 0 } },
      { source: pixelSortSource, constants: { axis: 1 } },
    ],
    params: pixelSortParams(false),
  },
  {
    id: "pixel-sort-vh",
    name: "Pixel sort (VH)",
    group: "Stylized",
    description:
      "Two-pass pixel sort: vertical, then horizontal — Kim Asendorf's original order. Same masked interval modes as Pixel sort.",
    usesLayerMask: true,
    passes: [
      { source: pixelSortSource, constants: { axis: 1 } },
      { source: pixelSortSource, constants: { axis: 0 } },
    ],
    params: pixelSortParams(false),
  },
  {
    id: "blur-gaussian",
    name: "Blur (Gaussian)",
    group: "Blur",
    description: "Separable Gaussian blur (horizontal then vertical pass).",
    passes: [
      { source: blurSeparableSource, constants: { axis: [1, 0], mode: 0 } },
      { source: blurSeparableSource, constants: { axis: [0, 1], mode: 0 } },
    ],
    params: [
      {
        type: "float",
        key: "radius",
        label: "Radius",
        min: 1,
        max: 24,
        step: 1,
        default: 8,
      },
      {
        type: "float",
        key: "sigma",
        label: "Sigma",
        min: 0.2,
        max: 16,
        step: 0.1,
        default: 4,
      },
    ],
  },
  {
    id: "blur-box",
    name: "Blur (box)",
    group: "Blur",
    description: "Separable box blur.",
    passes: [
      { source: blurSeparableSource, constants: { axis: [1, 0], mode: 1 } },
      { source: blurSeparableSource, constants: { axis: [0, 1], mode: 1 } },
    ],
    params: [
      {
        type: "float",
        key: "radius",
        label: "Radius",
        min: 1,
        max: 24,
        step: 1,
        default: 6,
      },
    ],
  },
  {
    id: "blur-kawase",
    name: "Blur (Kawase)",
    group: "Blur",
    description: "Wide Dual Kawase-style blur. Cheaper large-radius look than a Gaussian.",
    passes: [{ source: blurKawaseSource }, { source: blurKawaseSource }],
    params: [
      {
        type: "float",
        key: "offset",
        label: "Offset",
        min: 0.5,
        max: 12,
        step: 0.1,
        default: 2.5,
      },
    ],
  },
  {
    id: "blur-motion",
    name: "Blur (motion)",
    group: "Blur",
    description: "Directional streak along an angle.",
    source: blurMotionSource,
    params: [
      {
        type: "float",
        key: "distance",
        label: "Distance",
        min: 0,
        max: 200,
        step: 1,
        default: 24,
        description: "Streak length in source pixels.",
      },
      {
        type: "float",
        key: "angle",
        label: "Angle",
        min: 0,
        max: 6.2832,
        step: 0.01,
        default: 0,
        description: "Radians. 0 is to the right.",
      },
      {
        type: "int",
        key: "samples",
        label: "Samples",
        min: 3,
        max: 32,
        default: 12,
      },
    ],
  },
  {
    id: "hue",
    name: "Hue",
    group: "Color",
    description: "Rotate hues around the grey axis.",
    source: hueSource,
    params: [
      {
        type: "float",
        key: "degrees",
        label: "Degrees",
        min: -180,
        max: 180,
        step: 1,
        default: 0,
      },
    ],
  },
  {
    id: "contrast",
    name: "Contrast",
    group: "Color",
    description: "Scale RGB around mid-grey.",
    source: contrastSource,
    params: [
      {
        type: "float",
        key: "amount",
        label: "Amount",
        min: 0,
        max: 3,
        step: 0.01,
        default: 1,
      },
    ],
  },
  {
    id: "saturation",
    name: "Saturation",
    group: "Color",
    description: "0 is greyscale, 1 is original, above 1 pushes chroma.",
    source: saturationSource,
    params: [
      {
        type: "float",
        key: "amount",
        label: "Amount",
        min: 0,
        max: 3,
        step: 0.01,
        default: 1,
      },
    ],
  },
  {
    id: "grayscale",
    name: "Grayscale",
    group: "Color",
    description: "Mix towards luminance.",
    source: grayscaleSource,
    params: [
      {
        type: "float",
        key: "amount",
        label: "Amount",
        min: 0,
        max: 1,
        step: 0.01,
        default: 1,
      },
    ],
  },
  {
    id: "color-map",
    name: "Color map",
    group: "Color",
    description:
      "Remap the image onto a colour palette. WeatherNext 3 sky is the default; pick another preset or build a custom six-stop ramp.",
    source: colorMapSource,
    params: [
      {
        type: "select",
        key: "preset",
        label: "Palette",
        options: COLOR_MAP_PRESETS.map(({ value, label }) => ({ value, label })),
        default: 0,
        description: "Named ramps, or Custom to edit the six colour stops.",
      },
      ...COLOR_MAP_STOP_PARAMS,
      {
        type: "select",
        key: "mode",
        label: "Fit",
        options: [
          { value: 0, label: "Gradient" },
          { value: 1, label: "Nearest" },
        ],
        default: 0,
        description: "Gradient maps brightness along the ramp. Nearest snaps each pixel to the closest palette colour.",
      },
      {
        type: "select",
        key: "source",
        label: "Source",
        options: [
          { value: 0, label: "Luminance" },
          { value: 1, label: "Average" },
          { value: 2, label: "Value" },
        ],
        default: 0,
        description: "What drives the ramp in Gradient mode. Value is the max RGB channel.",
      },
      {
        type: "float",
        key: "strength",
        label: "Strength",
        min: 0,
        max: 1,
        step: 0.01,
        default: 1,
        description: "Mix back toward the original. 1 is a full palette remap.",
      },
      {
        type: "float",
        key: "gamma",
        label: "Gamma",
        min: 0.2,
        max: 4,
        step: 0.01,
        default: 1,
        description: "Curve applied to the lookup before sampling the ramp. >1 pushes midtones toward shadows.",
      },
      {
        type: "float",
        key: "smoothness",
        label: "Smoothness",
        min: 0,
        max: 1,
        step: 0.01,
        default: 1,
        description: "Gradient mode: 0 steps between stops, 1 interpolates. Ignored by Nearest.",
      },
      {
        type: "float",
        key: "dither",
        label: "Dither",
        min: 0,
        max: 0.25,
        step: 0.005,
        default: 0,
        description: "Ordered dither on the lookup, to break up banding in Gradient mode.",
      },
      {
        type: "float",
        key: "hue",
        label: "Hue",
        min: -180,
        max: 180,
        step: 1,
        default: 0,
        description: "Rotate the mapped palette around the grey axis, in degrees.",
      },
      { type: "bool", key: "invert", label: "Invert", default: false, description: "Flip the Gradient lookup." },
    ],
  },
  {
    id: "tint",
    name: "Tint",
    group: "Color",
    description: "Tint by luminance toward a colour.",
    source: tintSource,
    params: [
      { type: "color", key: "tint", label: "Tint", default: [1, 0.72, 0.45] },
      {
        type: "float",
        key: "strength",
        label: "Strength",
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.35,
      },
    ],
  },
  {
    id: "opacity",
    name: "Opacity",
    group: "Color",
    description: "Multiply the layer alpha. Combine with a mask for fades.",
    source: opacitySource,
    params: [
      {
        type: "float",
        key: "amount",
        label: "Amount",
        min: 0,
        max: 1,
        step: 0.01,
        default: 1,
      },
    ],
  },
  {
    id: "grain",
    name: "Grain",
    group: "Atmosphere",
    description: "Film-like luminance grain. Enable animated for video.",
    source: grainSource,
    params: [
      {
        type: "float",
        key: "amount",
        label: "Amount",
        min: 0,
        max: 0.4,
        step: 0.005,
        default: 0.08,
      },
      {
        type: "float",
        key: "size",
        label: "Size",
        min: 0.5,
        max: 8,
        step: 0.1,
        default: 1,
      },
      { type: "bool", key: "animated", label: "Animated", default: false },
    ],
  },
  {
    id: "vignette",
    name: "Vignette",
    group: "Atmosphere",
    description: "Darken the frame edges.",
    source: vignetteSource,
    params: [
      {
        type: "float",
        key: "intensity",
        label: "Intensity",
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.45,
      },
      {
        type: "float",
        key: "roundness",
        label: "Roundness",
        min: 0,
        max: 1,
        step: 0.01,
        default: 1,
      },
      {
        type: "float",
        key: "smoothness",
        label: "Smoothness",
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.45,
      },
    ],
  },
  {
    id: "bloom",
    name: "Bloom",
    group: "Atmosphere",
    description: "Extract highlights, blur them, and add them back. Four GPU passes.",
    passes: [
      { source: bloomExtractSource },
      { source: blurSeparableSource, constants: { axis: [1, 0], mode: 0 } },
      { source: blurSeparableSource, constants: { axis: [0, 1], mode: 0 } },
      { source: bloomCompositeSource },
    ],
    params: [
      {
        type: "float",
        key: "threshold",
        label: "Threshold",
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.7,
      },
      {
        type: "float",
        key: "radius",
        label: "Radius",
        min: 1,
        max: 24,
        step: 1,
        default: 12,
      },
      {
        type: "float",
        key: "sigma",
        label: "Sigma",
        min: 0.2,
        max: 16,
        step: 0.1,
        default: 6,
      },
      {
        type: "float",
        key: "strength",
        label: "Strength",
        min: 0,
        max: 4,
        step: 0.01,
        default: 0.8,
      },
    ],
  },
];
