import type { ParamDef, ShaderDefinition } from "@/lib/shaders/registry";
import { IDENTITY_CURVE, type ColorRangeValue } from "@/lib/shaders/param-values";
import tinyLightroomSource from "@/lib/shaders/wgsl/tiny-lightroom.wgsl";

const slider = (
  key: string,
  label: string,
  min: number,
  max: number,
  step: number,
  section: string,
  description?: string,
): ParamDef => ({
  type: "float",
  key,
  label,
  section,
  min,
  max,
  step,
  default: 0,
  description,
});

const band = (
  key: string,
  label: string,
  color: [number, number, number],
  start: number,
  end: number,
  softness: number,
): ParamDef[] => {
  const range: ColorRangeValue = { color, start, end, softness };
  const section = label;
  return [
    {
      type: "colorRange",
      key: `${key}_range`,
      label: `${label} range`,
      section,
      sectionCollapsed: true,
      default: range,
      description: "Hue window this band adjusts. Drag the edges, or pick a color to recenter it.",
    },
    slider(`${key}_hue`, "Hue", -100, 100, 1, section, "Shifts hues inside the window, ±40° at the ends."),
    slider(`${key}_sat`, "Saturation", -100, 100, 1, section),
    slider(`${key}_lum`, "Luminance", -100, 100, 1, section),
  ];
};

const curve = (key: string, label: string): ParamDef => ({
  type: "curve",
  key,
  label,
  section: "Curves",
  default: IDENTITY_CURVE.map((p) => ({ ...p })),
  description: "Drag knots. Double-click a knot to remove it. Click the grid to add one.",
});

export const TINY_LIGHTROOM: ShaderDefinition = {
  id: "tiny-lightroom",
  name: "Tiny Lightroom",
  group: "Color",
  description:
    "Photo grade: exposure and tone, white balance, tone curves, per-hue ranges, color grading, clarity, dehaze, vignette, and grain.",
  source: tinyLightroomSource,
  params: [
    {
      type: "float",
      key: "strength",
      label: "Strength",
      section: "Mix",
      min: 0,
      max: 1,
      step: 0.01,
      default: 1,
      description: "Mix back toward the original image.",
    },
    slider("exposure", "Exposure", -2, 2, 0.01, "Light", "Stops. 0 leaves the image unchanged."),
    slider("contrast", "Contrast", -100, 100, 1, "Light"),
    slider("highlights", "Highlights", -100, 100, 1, "Light"),
    slider("shadows", "Shadows", -100, 100, 1, "Light"),
    slider("whites", "Whites", -100, 100, 1, "Light"),
    slider("blacks", "Blacks", -100, 100, 1, "Light"),
    slider("temperature", "Temp", -100, 100, 1, "Color", "Negative is cooler, positive is warmer."),
    slider("tint", "Tint", -100, 100, 1, "Color", "Negative is green, positive is magenta."),
    slider("vibrance", "Vibrance", -100, 100, 1, "Color", "Saturation that favors muted colors."),
    slider("saturation", "Saturation", -100, 100, 1, "Color"),
    curve("tone_curve", "Tone"),
    curve("red_curve", "Red"),
    curve("green_curve", "Green"),
    curve("blue_curve", "Blue"),
    {
      type: "color",
      key: "shadow_color",
      label: "Shadows",
      section: "Grade",
      default: [0.5, 0.5, 0.5],
    },
    {
      type: "float",
      key: "shadow_amount",
      label: "Shadows amount",
      section: "Grade",
      min: 0,
      max: 1,
      step: 0.01,
      default: 0,
    },
    {
      type: "color",
      key: "mid_color",
      label: "Midtones",
      section: "Grade",
      default: [0.5, 0.5, 0.5],
    },
    {
      type: "float",
      key: "mid_amount",
      label: "Midtones amount",
      section: "Grade",
      min: 0,
      max: 1,
      step: 0.01,
      default: 0,
    },
    {
      type: "color",
      key: "high_color",
      label: "Highlights",
      section: "Grade",
      default: [0.5, 0.5, 0.5],
    },
    {
      type: "float",
      key: "high_amount",
      label: "Highlights amount",
      section: "Grade",
      min: 0,
      max: 1,
      step: 0.01,
      default: 0,
    },
    {
      type: "color",
      key: "global_color",
      label: "Global",
      section: "Grade",
      default: [0.5, 0.5, 0.5],
    },
    {
      type: "float",
      key: "global_amount",
      label: "Global amount",
      section: "Grade",
      min: 0,
      max: 1,
      step: 0.01,
      default: 0,
    },
    slider("balance", "Balance", -100, 100, 1, "Grade", "Shifts the split between shadows and highlights."),
    slider("texture_amt", "Texture", -100, 100, 1, "Effects", "Fine local contrast."),
    slider("clarity", "Clarity", -100, 100, 1, "Effects", "Broader midtone contrast."),
    slider("dehaze", "Dehaze", -100, 100, 1, "Effects"),
    slider("vignette", "Vignette", -100, 100, 1, "Effects", "Positive darkens the edges, negative lightens them."),
    {
      type: "float",
      key: "vignette_feather",
      label: "Vignette feather",
      section: "Effects",
      min: 0,
      max: 100,
      step: 1,
      default: 55,
    },
    slider("grain", "Grain", 0, 100, 1, "Effects"),
    {
      type: "float",
      key: "grain_size",
      label: "Grain size",
      section: "Effects",
      min: 0.5,
      max: 6,
      step: 0.05,
      default: 1.25,
    },
    ...band("red", "Red", [0.93, 0.18, 0.16], 0.94, 0.06, 0.035),
    ...band("orange", "Orange", [0.95, 0.48, 0.12], 0.04, 0.14, 0.03),
    ...band("yellow", "Yellow", [0.96, 0.82, 0.18], 0.12, 0.22, 0.03),
    ...band("green", "Green", [0.28, 0.78, 0.28], 0.22, 0.46, 0.04),
    ...band("aqua", "Aqua", [0.16, 0.74, 0.78], 0.44, 0.58, 0.035),
    ...band("blue", "Blue", [0.22, 0.42, 0.95], 0.56, 0.72, 0.035),
    ...band("purple", "Purple", [0.58, 0.28, 0.9], 0.7, 0.84, 0.035),
    ...band("magenta", "Magenta", [0.9, 0.22, 0.72], 0.82, 0.96, 0.035),
  ],
};
